# https://github.com/intent-driven-dev/openspec-schemas
# schema: intent-driven
schema: spec-driven-with-adr

#   context: |
#     Tech stack: TypeScript, React, Node.js
#     We use conventional commits
#     Domain: e-commerce platform

rules:
  proposal:
    - Must use grill-me skill
    - Must use adversarial-authoring skill
    - Must use glossary skill
  specs:
    - Must use spec-as-source skill
  design:
    - Must use c4-diagrams skill
    - Must use glossary skill
  adr:
    - Must use architectural-decision-records skill
  tasks:
    - Must use spec-as-source skill
